apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heatpump-data
  namespace: heatpump
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
