apiVersion: v1
kind: Service
metadata:
  name: heatpump-exporter
  namespace: heatpump
  labels:
    app: heatpump-exporter
spec:
  type: NodePort
  selector:
    app: heatpump-exporter
  ports:
    - name: metrics
      port: 9105
      targetPort: 9105
      nodePort: 30105
